# Generated by Django 3.2.23 on 2023-12-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231221_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favourite_band',
            new_name='favourite_artist',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='favouruite_song',
            new_name='favourite_song',
        ),
    ]
