# Generated by Django 3.2.23 on 2023-12-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite_album',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favourite_artist',
        ),
    ]
