# Generated by Django 3.2.23 on 2023-12-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20231222_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite_song',
        ),
        migrations.AddField(
            model_name='profile',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
