# Generated by Django 3.2.23 on 2023-12-28 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20231228_2213'),
        ('profiles', '0004_auto_20231228_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.song'),
        ),
    ]
