# Generated by Django 3.2.23 on 2023-12-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_favourite_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite_song',
        ),
    ]
