# Generated by Django 3.2.23 on 2023-12-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20231228_2219'),
        ('profiles', '0007_remove_profile_favourite_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.album'),
        ),
    ]
