# Generated by Django 3.2.23 on 2023-12-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_favourite_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='content',
        ),
    ]
