# Generated by Django 3.2.23 on 2023-12-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_artist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
    ]
