# Generated by Django 3.2.23 on 2023-12-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_artist_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
