# Generated by Django 3.2.23 on 2023-12-28 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20231228_2054'),
        ('music', '0003_remove_song_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
