# Generated by Django 3.2.23 on 2023-12-28 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
