# Generated by Django 3.2.23 on 2024-01-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20231229_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='review',
        ),
    ]
